apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-https-echo
  labels:
    app: http-https-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-https-echo
  template:
    metadata:
      labels:
        app: http-https-echo
    spec:
      containers:
name: echo-server
          image: hashicorp/http-echo:latest
          args:
"-text=Hello from http-https-echo"
          ports:
containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-https-echo
  labels:
    app: http-https-echo
spec:
  type: ClusterIP
  selector:
    app: http-https-echo
  ports:
name: http
      port: 80
      targetPort: 80
