apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-https-echo
  template:
    metadata:
      labels:
        app: http-https-echo
    spec:
      containers:
      - name: http-echo
        image: mendhak/http-https-echo:31
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
spec:
  selector:
    app: http-https-echo
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8080
  type: LoadBalancer
